### ISSUE TITLE
Webpack config missing?

### ISSUE THREAD

**Issue by bhellman1** [timscott/react-devise-sample#1]
Hello, from the readme: "This project setup uses Webpack for handling all assets." --- where is the project's webpack config file? I'm looking to add `css-loader` to the sample app but don't see where in the sample app the webpack config exists. Thanks

**Comment by timscott** [comment]
This app uses [`create-react-app`](https://github.com/facebookincubator/create-react-app) which hides webpack config. The [README](https://github.com/facebookincubator/create-react-app) explains about it. You can run `yarn run eject` to see and edit webpack config. The point is to avoid that as long as possible.

**Comment by bhellman1** [comment]
Thanks Tim, I appreciate the reply, answer and explanation.
